# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-18 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submit', '0002_review_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('slug', models.SlugField(help_text=b'Must be unique among all tasks, serves as part of URL.<br />By default, task.slug is also used as a name of inputs folder at judge.<br />Must only contain characters "a-zA-Z0-9_-".', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('visible', models.BooleanField()),
                ('deadline', models.DateTimeField()),
                ('max_points', models.IntegerField()),
                ('submit_receivers', models.ManyToManyField(to='submit.SubmitReceiver')),
            ],
        ),
    ]
