# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-11 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='submit_receivers',
        ),
    ]
