# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-11 17:04
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_submit_receivers'),
        ('submit', '0002_review_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitreceiver',
            name='task',
            field=models.ForeignKey(default='task-with-multiple-receivers', on_delete=django.db.models.deletion.CASCADE, to='tasks.Task'),
            preserve_default=False,
        ),
    ]
