# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-15 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0003_submitreceiver_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubmitReceiverTemplate',
        ),
        migrations.AlterField(
            model_name='review',
            name='short_response',
            field=models.CharField(blank=True, choices=[('Manual review', ((b'Reviewed', 'Reviewed'),)), ('Judge test results', [(b'OK', 'OK'), (b'EXC', 'Runtime exception'), (b'WA', 'Wrong answer'), (b'CERR', 'Compilation error'), (b'SEC', 'Security exception'), (b'TLE', 'Time limit exceeded'), (b'IGN', 'Ignored')]), ('Judge communication', [(b'Sending to judge', 'Sending to judge'), (b'Sent to judge', 'Sent to judge'), (b'Judge unavailable', 'Judge unavailable'), (b'Protocol corrupted', 'Protocol corrupted')])], max_length=128),
        ),
    ]
