# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-15 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0004_auto_20170215_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitreceiver',
            name='configuration',
        ),
        migrations.AddField(
            model_name='submitreceiver',
            name='caption',
            field=models.CharField(blank=True, default=b'', help_text='Text that appears on the left from submit form.', max_length=128),
        ),
        migrations.AddField(
            model_name='submitreceiver',
            name='extensions',
            field=models.CharField(blank=True, default=b'', help_text='List of comma separated extensions e.g. "txt, pdf, doc".<br />Leave blank to accept any extension.', max_length=256),
        ),
        migrations.AddField(
            model_name='submitreceiver',
            name='external_link',
            field=models.CharField(blank=True, default=b'', help_text='URL for external submits. A button with link will be rendered in the submit form.', max_length=256),
        ),
        migrations.AddField(
            model_name='submitreceiver',
            name='has_form',
            field=models.BooleanField(default=False, help_text='Check to collect files via submit form.'),
        ),
        migrations.AddField(
            model_name='submitreceiver',
            name='inputs_folder_at_judge',
            field=models.CharField(blank=True, default=b'', help_text='If left blank, and send_to_judge is checked, this field will be set automatically.', max_length=128),
        ),
        migrations.AddField(
            model_name='submitreceiver',
            name='languages',
            field=models.CharField(blank=True, default=b'', help_text='List of comma separated programming language extensions e.g. "c, cpp, py, hs".<br />Use languages supported by the judge from [\'.c\', \'.cs\', \'.java\', \'.py\', \'.hs\', \'.pas\', \'.cc\', \'.zip\']<br />', max_length=256),
        ),
        migrations.AddField(
            model_name='submitreceiver',
            name='send_to_judge',
            field=models.BooleanField(default=False, help_text='Check to send submits to automated judge.'),
        ),
        migrations.AddField(
            model_name='submitreceiver',
            name='show_all_details',
            field=models.BooleanField(default=False, help_text='Check to display protocol details to all users.'),
        ),
        migrations.AddField(
            model_name='submitreceiver',
            name='show_submitted_file',
            field=models.BooleanField(default=False, help_text='Check to render submitted file as a part of web page for submit.'),
        ),
    ]
