# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-16 18:11
from __future__ import unicode_literals

from django.db import migrations, models

import submit.models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0005_auto_20170215_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitreceiver',
            name='languages',
            field=models.CharField(blank=True, default=b'', help_text='List of comma separated programming language extensions e.g. "c, cpp, py, hs".<br />Use languages supported by the judge from: c, pas, java, cc, hs, py, cs.<br />When languages are set, field "extensions" is ignored.', max_length=256, validators=[submit.models.validate_languages]),
        ),
    ]
